name: hgb
version: 0.1.0.0
github: "ayazhafiz/hgb"
license: BSD3
author: "Lukas Berglund, Ayaz Hafiz"
maintainer: "ayaz.hafiz.1@gmail.com"
copyright: "2019 Berglund, hafiz"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Please see the README on GitHub at <https://github.com/githubuser/hgb#readme>

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src

executables:
  hgb-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hgb

tests:
  hgb-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hgb
      - tasty
